version: "3.9"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    container_name: loresmith_api_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - CACHE_KEY_PREFIX=${CACHE_KEY_PREFIX}
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14-alpine
    container_name: loresmith_api_db
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme

  redis:
    image: redis:7-alpine
    container_name: loresmith_api_redis
    ports:
      - "6379:6379"

volumes:
  dev-db-data:
